-- Top 5 Customers by Total Spending
-- Business Question:
-- Which customers have spent the most on food orders?
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.order_amount) AS total_spent
FROM food_orders o
JOIN food_customers c 
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 5;

-- Revenue Generated by Each Restaurant
-- Business Question:
-- How much revenue has each restaurant generated?
SELECT 
    r.restaurant_id,
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    COUNT(o.order_id) AS total_orders
FROM food_orders o
JOIN food_restaurants r 
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;

-- Average Delivery Time by Delivery Partner
-- Business Question:
-- Which delivery partners are performing better based on average delivery time?
SELECT 
    p.partner_id,
    p.partner_name,
    AVG(o.delivery_time_minutes) AS avg_delivery_time
FROM food_orders o
JOIN food_delivery_partners p
    ON o.partner_id = p.partner_id
GROUP BY p.partner_id, p.partner_name
ORDER BY avg_delivery_time ASC;

-- Monthly Revenue Trend (Year-wise)
-- Business Question:
-- What is the monthly revenue trend?
SELECT 
    YEAR(order_date) AS order_year,
    MONTH(order_date) AS order_month,
    SUM(order_amount) AS monthly_revenue
FROM food_orders
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY order_year, order_month;

-- Rank Restaurants Based on Revenue (Window Function)
-- Business Question:
-- Rank restaurants based on total revenue.
SELECT 
    r.restaurant_name,
    SUM(o.order_amount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(o.order_amount) DESC) AS revenue_rank
FROM food_orders o
JOIN food_restaurants r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_name;

-- Customer Retention Analysis (Repeat Customers)
-- Business Question:
-- Find customers who placed more than 5 orders (loyal customers).
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM food_orders o
JOIN food_customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 5
ORDER BY total_orders DESC;

-- Running Total of Revenue Over Time(Bonus question)
SELECT 
    order_date,
    SUM(order_amount) AS daily_revenue,
    SUM(SUM(order_amount)) OVER (ORDER BY order_date) AS running_total
FROM food_orders
GROUP BY order_date
ORDER BY order_date;